# Generated by Django 3.0.8 on 2020-10-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tamanho', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('vltotal', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor Total')),
                ('vlquota', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Valor Quota')),
                ('vlpatrimliq', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor Pat Liq')),
                ('captcdia', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Captc Dia')),
                ('resgdia', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Resgate Dia')),
                ('nrcotst', models.IntegerField(blank=True, null=True, verbose_name='Nr Cotst')),
            ],
        ),
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=200)),
                ('resgate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
            ],
        ),
    ]
