# Generated by Django 3.0.8 on 2020-10-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='vlquota',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=15, null=True, verbose_name='Valor Quota'),
        ),
    ]
