# Generated by Django 3.0.8 on 2020-10-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201028_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='denom_social',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Denominação Social'),
        ),
    ]
