# Generated by Django 3.0.8 on 2020-10-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dados_denom_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='resgdia',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Resgate Dia'),
        ),
    ]
