# Generated by Django 3.0.8 on 2020-08-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('data', models.DateField(verbose_name='Data')),
            ],
        ),
    ]
