# Generated by Django 3.0.8 on 2020-08-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200804_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='vlquota',
            field=models.DecimalField(decimal_places=20, max_digits=20, verbose_name='Valor Quota'),
        ),
    ]
