# Generated by Django 3.0.8 on 2020-08-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200804_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='data',
        ),
    ]
